import { getThemeTokens } from '../../components/ui/themeTokens';

// Style functions for dark mode support
export const chatWindowStyles = {
  appWrap: (dark: boolean): React.CSSProperties => {
    const t = getThemeTokens(dark);
    return { display: 'flex', flexDirection: 'column', height: '100vh', overflow: 'hidden', background: t.bgBase };
  },
  layout: (dark: boolean): React.CSSProperties => {
    const t = getThemeTokens(dark);
    return { display: 'flex', flexDirection: 'column', flex: 1, minHeight: 0, background: t.bgBase, position: 'relative' };
  },
  loading: (dark: boolean): React.CSSProperties => ({ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: getThemeTokens(dark).textMuted, fontSize: 16 }),
  chatHeader: (dark: boolean, compact = false): React.CSSProperties => {
    const t = getThemeTokens(dark);
    return {
      padding: compact ? '8px 12px' : '0 20px',
      minHeight: 56,
      borderBottom: `1px solid ${t.border}`,
      background: t.bgSurface,
      boxShadow: dark ? 'none' : '0 1px 3px rgba(0,0,0,0.04)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: compact ? 8 : 12,
      flexWrap: compact ? 'wrap' : 'nowrap',
    };
  },
  chatHeaderName: (dark: boolean): React.CSSProperties => ({ fontSize: 16, fontWeight: 700, color: getThemeTokens(dark).textStrong, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', letterSpacing: '-0.01em' }),
  headerIconBtn: (dark: boolean, compact = false): React.CSSProperties => ({
    width: compact ? 32 : 34,
    height: compact ? 32 : 34,
    borderRadius: 8,
    border: 'none',
    background: dark ? '#334155' : '#fff',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    transition: 'background 0.15s'
  }),
  messages: (dark: boolean): React.CSSProperties => ({ flex: 1, overflowX: 'hidden', overflowY: 'auto', padding: '16px 20px', display: 'flex', flexDirection: 'column', gap: 10, background: getThemeTokens(dark).bgBase }),
  scrollToBottomBtn: (dark: boolean): React.CSSProperties => ({
    position: 'absolute',
    bottom: 16,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: '50%',
    border: 'none',
    background: dark ? '#334155' : '#fff',
    color: dark ? '#e2e8f0' : '#475569',
    boxShadow: '0 2px 12px rgba(0,0,0,0.15)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  }),
  dateSeparator: (): React.CSSProperties => ({ display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '12px 0' }),
  dateSeparatorText: (): React.CSSProperties => ({ fontSize: 12, color: '#fff', background: 'rgba(0,0,0,0.25)', padding: '4px 14px', borderRadius: 12 }),
  unreadDivider: (dark: boolean): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '10px 16px',
    margin: '8px 16px',
    borderLeft: '4px solid #171717',
    background: dark ? 'rgba(99,102,241,0.15)' : 'rgba(99,102,241,0.1)',
    borderRadius: 8,
    animation: 'unread-divider-pulse 2s ease-in-out 3',
  }),
  unreadDividerText: (dark: boolean): React.CSSProperties => ({
    fontSize: 12,
    fontWeight: 600,
    color: dark ? '#e0e7ff' : '#171717',
  }),
  systemMessageRow: (): React.CSSProperties => ({ display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '6px 0' }),
  systemMessageText: (): React.CSSProperties => ({ fontSize: 12, color: '#fff', background: 'rgba(0,0,0,0.25)', padding: '4px 14px', borderRadius: 12, textAlign: 'center' }),
  messageRow: (): React.CSSProperties => ({ display: 'flex', flexDirection: 'column', alignItems: 'flex-start', width: '100%' }),
  messageRowMine: (): React.CSSProperties => ({ alignItems: 'flex-end' }),
  messageRowInner: (): React.CSSProperties => ({ display: 'flex', alignItems: 'flex-start', gap: 8, width: '100%' }),
  avatarWrap: (): React.CSSProperties => ({ width: 34, height: 34, flexShrink: 0 }),
  avatarSpacer: (): React.CSSProperties => ({ width: 34, height: 34, flexShrink: 0 }),
  avatarCircle: (dark: boolean): React.CSSProperties => ({ width: 34, height: 34, borderRadius: '50%', background: dark ? '#334155' : '#e2e8f0', color: dark ? '#94a3b8' : '#475569', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 13, fontWeight: 700 }),
  messageBubble: (dark: boolean): React.CSSProperties => ({ minWidth: 80, padding: '10px 14px', borderRadius: 16, borderTopLeftRadius: 4, background: dark ? '#334155' : '#fff', color: dark ? '#e2e8f0' : '#1e293b', boxShadow: dark ? '0 1px 3px rgba(0,0,0,0.15)' : '0 1px 4px rgba(0,0,0,0.06)', wordBreak: 'break-word', overflowWrap: 'break-word' }),
  messageBubbleMine: (dark: boolean): React.CSSProperties => ({ borderTopLeftRadius: 16, borderTopRightRadius: 4, background: dark ? '#475569' : '#475569', color: '#fff', boxShadow: '0 1px 4px rgba(0,0,0,0.12)' }),
  senderLabel: (dark: boolean): React.CSSProperties => ({
    fontSize: 12,
    color: dark ? '#cbd5e1' : '#475569',
    marginBottom: 4,
    marginLeft: 42,
    maxWidth: 'calc(75% - 8px)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  metaCol: (): React.CSSProperties => ({ display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: 4, fontSize: 11, color: '#64748b', flexShrink: 0, minWidth: 36 }),
  metaColMine: (): React.CSSProperties => ({ alignItems: 'flex-end' }),
  metaTime: (dark: boolean): React.CSSProperties => ({ fontSize: 11, color: dark ? '#cbd5e1' : '#64748b' }),
  messageContent: (): React.CSSProperties => ({ whiteSpace: 'pre-wrap', wordBreak: 'break-word', fontSize: 15, lineHeight: 1.4 }),
  // Board card footer background is neutral, so use accent color.
  readStatusMineBoard: (dark: boolean): React.CSSProperties => ({ fontSize: 12, fontWeight: 700, color: getThemeTokens(dark).primary }),
  // My chat bubble background is slate (#475569), so keep unread count near-white for contrast.
  readStatusMineBubble: (): React.CSSProperties => ({ fontSize: 12, fontWeight: 700, color: '#f8fafc' }),
  replyPreview: (dark: boolean, isMine: boolean): React.CSSProperties => ({
    marginLeft: isMine ? 0 : 42,
    marginBottom: 6,
    padding: '8px 12px',
    borderRadius: 10,
    background: dark ? 'rgba(71, 85, 105, 0.7)' : 'rgba(241, 245, 249, 0.9)',
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    maxWidth: '85%',
    overflow: 'hidden',
    boxShadow: dark ? '0 1px 2px rgba(0,0,0,0.1)' : '0 1px 3px rgba(0,0,0,0.06)',
    cursor: 'pointer',
  }),
  replyPreviewLabel: (dark: boolean): React.CSSProperties => ({
    fontSize: 11,
    fontWeight: 600,
    color: dark ? '#e2e8f0' : '#64748b',
    letterSpacing: '0.02em',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  replyPreviewContent: (dark: boolean): React.CSSProperties => ({
    fontSize: 13,
    color: dark ? '#f1f5f9' : '#475569',
    lineHeight: 1.35,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    wordBreak: 'break-word',
    overflowWrap: 'anywhere',
  }),
  reactionsRow: (isMine: boolean): React.CSSProperties => ({ display: 'flex', gap: 4, flexWrap: 'wrap', marginLeft: isMine ? 0 : 42, marginTop: 4 }),
  reactionBadge: (dark: boolean, voted: boolean): React.CSSProperties => ({ border: `1px solid ${voted ? (dark ? '#60a5fa' : '#2563eb') : (dark ? '#475569' : '#e5e7eb')}`, borderRadius: 12, padding: '2px 8px', fontSize: 13, background: voted ? (dark ? 'rgba(96,165,250,0.15)' : 'rgba(37,99,235,0.08)') : 'transparent', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4 }),
  hoverActionBtn: (dark: boolean): React.CSSProperties => ({
    width: 32,
    height: 32,
    borderRadius: '50%',
    border: 'none',
    background: dark ? '#64748b' : '#f0f0f0',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    color: dark ? '#f8fafc' : '#555',
    padding: 0,
    boxShadow: dark ? '0 1px 3px rgba(0,0,0,0.25)' : 'none',
  }),
  ctxMenu: (dark: boolean): React.CSSProperties => ({ position: 'fixed', zIndex: 10000, minWidth: 120, padding: 4, background: dark ? '#334155' : '#fff', borderRadius: 8, boxShadow: '0 4px 20px rgba(0,0,0,0.15)', border: `1px solid ${dark ? '#475569' : '#eee'}` }),
  ctxMenuItem: (dark: boolean): React.CSSProperties => ({ display: 'block', width: '100%', padding: '8px 12px', border: 'none', background: 'none', borderRadius: 6, fontSize: 13, color: dark ? '#e2e8f0' : '#333', textAlign: 'left', cursor: 'pointer' }),
  searchBar: (dark: boolean): React.CSSProperties => ({ display: 'flex', gap: 6, padding: '8px 16px', borderBottom: `1px solid ${getThemeTokens(dark).border}`, background: getThemeTokens(dark).bgSurface }),
  searchInput: (dark: boolean): React.CSSProperties => ({ flex: 1, padding: '8px 12px', border: `1px solid ${getThemeTokens(dark).border}`, borderRadius: 8, fontSize: 13, background: getThemeTokens(dark).bgMuted, color: getThemeTokens(dark).text, outline: 'none' }),
  searchBtn: (dark: boolean): React.CSSProperties => ({
    height: 32,
    minHeight: 32,
    padding: '0 14px',
    border: 'none',
    borderRadius: 8,
    background: getThemeTokens(dark).primary,
    color: '#fff',
    fontSize: 13,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    lineHeight: 1,
  }),
  searchResults: (dark: boolean): React.CSSProperties => ({ maxHeight: 200, overflow: 'auto', borderBottom: `1px solid ${dark ? '#334155' : '#eee'}`, background: dark ? '#1e293b' : '#fff' }),
  searchResultItem: (dark: boolean): React.CSSProperties => ({ display: 'flex', alignItems: 'center', gap: 4, padding: '8px 16px', borderBottom: `1px solid ${dark ? '#334155' : '#f0f0f0'}`, fontSize: 13 }),
  replyIndicator: (dark: boolean): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    padding: '8px 16px',
    borderTop: `1px solid ${dark ? '#334155' : '#eee'}`,
    background: dark ? '#1e293b' : '#f8fafc',
  }),
  inputRow: (dark: boolean): React.CSSProperties => ({
    padding: '10px 16px 14px',
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    background: getThemeTokens(dark).bgSurface,
    borderTop: `1px solid ${getThemeTokens(dark).border}`,
  }),
  inputRowLeft: (): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  }),
  inputRowCenter: (): React.CSSProperties => ({
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
  }),
  inputRowRight: (): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexShrink: 0,
  }),
  plusWrap: (): React.CSSProperties => ({ position: 'relative', flexShrink: 0 }),
  plusBtn: (dark: boolean): React.CSSProperties => ({
    width: 40,
    height: 40,
    borderRadius: '50%',
    border: 'none',
    background: dark ? '#334155' : '#f1f5f9',
    color: dark ? '#94a3b8' : '#475569',
    fontSize: 20,
    lineHeight: '40px',
    textAlign: 'center',
    cursor: 'pointer',
    transition: 'background 0.15s',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  plusMenu: (dark: boolean): React.CSSProperties => ({ position: 'absolute', bottom: 48, left: 0, background: dark ? '#334155' : '#fff', border: `1px solid ${dark ? '#475569' : '#e2e8f0'}`, borderRadius: 12, boxShadow: dark ? '0 6px 24px rgba(0,0,0,0.3)' : '0 6px 24px rgba(0,0,0,0.1)', padding: 6, display: 'flex', flexDirection: 'column', gap: 2, minWidth: 150, zIndex: 50 }),
  plusMenuItem: (dark: boolean): React.CSSProperties => ({ border: 'none', background: 'transparent', borderRadius: 8, padding: '9px 12px', textAlign: 'left', cursor: 'pointer', fontSize: 13, color: dark ? '#e2e8f0' : '#334155', transition: 'background 0.1s' }),
  input: (dark: boolean): React.CSSProperties => ({
    width: '100%',
    padding: '10px 16px',
    border: `1px solid ${dark ? '#475569' : '#e2e8f0'}`,
    borderRadius: 20,
    fontSize: 14,
    lineHeight: 1.4,
    minHeight: 42,
    maxHeight: 120,
    resize: 'none',
    background: dark ? '#0f172a' : '#f8fafc',
    color: dark ? '#e2e8f0' : '#1e293b',
    outline: 'none',
    transition: 'border-color 0.15s, box-shadow 0.15s',
    fontFamily: 'inherit',
  }),
  sendBtn: (dark: boolean, disabled: boolean): React.CSSProperties => ({
    padding: '10px 20px',
    background: disabled ? (dark ? '#334155' : '#cbd5e1') : '#475569',
    color: '#fff',
    border: 'none',
    borderRadius: 20,
    fontWeight: 700,
    cursor: disabled ? 'not-allowed' : 'pointer',
    fontSize: 14,
    transition: 'background 0.15s, opacity 0.15s',
    opacity: disabled ? 0.9 : 1,
    whiteSpace: 'nowrap',
  }),
  dropOverlay: (): React.CSSProperties => ({ position: 'absolute', inset: 0, zIndex: 100, background: 'rgba(0,0,0,0.6)', display: 'flex', alignItems: 'center', justifyContent: 'center', pointerEvents: 'none' }),
  dropContent: (): React.CSSProperties => ({ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12 }),
  dropText: (): React.CSSProperties => ({ color: '#fff', fontSize: 16, fontWeight: 600 }),
  shareEventOverlay: (): React.CSSProperties => ({ position: 'absolute', inset: 0, zIndex: 200, background: 'rgba(0,0,0,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center' }),
  shareEventModal: (dark: boolean): React.CSSProperties => ({ background: dark ? '#1e293b' : '#fff', borderRadius: 12, boxShadow: '0 8px 32px rgba(0,0,0,0.2)', minWidth: 320, maxWidth: '90%', maxHeight: '70vh', overflow: 'auto', padding: 20 }),
  boardCard: (dark: boolean): React.CSSProperties => ({
    width: '100%',
    maxWidth: '100%',
    padding: 16,
    borderRadius: 12,
    background: dark ? '#1e293b' : '#fff',
    border: `1px solid ${dark ? '#334155' : '#e5e7eb'}`,
    boxShadow: dark ? '0 1px 3px rgba(0,0,0,0.12)' : '0 1px 3px rgba(0,0,0,0.08)',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  }),
  boardCardHeader: (dark: boolean): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flexWrap: 'wrap',
    borderColor: dark ? 'transparent' : 'transparent',
  }),
  boardCardHeaderLeft: (dark: boolean): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    minWidth: 0,
    color: dark ? 'inherit' : 'inherit',
  }),
  boardCardAvatar: (dark: boolean): React.CSSProperties => ({
    width: 40,
    height: 40,
    borderRadius: '50%',
    background: dark ? '#334155' : '#e5e7eb',
    color: dark ? '#94a3b8' : '#6b7280',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 15,
    fontWeight: 700,
    flexShrink: 0,
  }),
  boardCardAuthor: (dark: boolean): React.CSSProperties => ({
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    minWidth: 0,
    color: dark ? 'inherit' : 'inherit',
  }),
  boardCardAuthorName: (dark: boolean): React.CSSProperties => ({ fontSize: 14, fontWeight: 600, color: dark ? '#e2e8f0' : '#111827' }),
  boardCardTime: (dark: boolean): React.CSSProperties => ({ fontSize: 12, color: dark ? '#94a3b8' : '#6b7280', flexShrink: 0 }),
  boardCardBody: (dark: boolean): React.CSSProperties => ({
    fontSize: 14,
    color: dark ? '#e2e8f0' : '#374151',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    lineHeight: 1.6,
    paddingLeft: 0,
  }),
  boardCardFooter: (dark: boolean): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
    paddingTop: 8,
    borderTop: `1px solid ${dark ? '#334155' : '#e5e7eb'}`,
    fontSize: 12,
    color: dark ? '#94a3b8' : '#6b7280',
  }),
  boardCardFooterBtn: (dark: boolean): React.CSSProperties => ({
    padding: '4px 10px',
    border: `1px solid ${dark ? '#475569' : '#e5e7eb'}`,
    borderRadius: 8,
    background: dark ? '#334155' : '#f9fafb',
    color: dark ? '#94a3b8' : '#6b7280',
    fontSize: 12,
    cursor: 'pointer',
  }),
  boardMenuBtn: (dark: boolean): React.CSSProperties => ({
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    padding: 6,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background 0.15s',
    flexShrink: 0,
    ...(dark ? {} : {}),
  }),
  boardCommentSection: (dark: boolean): React.CSSProperties => ({
    borderTop: `1px solid ${dark ? '#334155' : '#e5e7eb'}`,
    paddingTop: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  }),
  boardCommentRow: (dark: boolean): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    padding: '4px 0',
    borderBottom: `1px solid ${dark ? 'rgba(51,65,85,0.4)' : 'rgba(229,231,235,0.6)'}`,
    paddingBottom: 10,
  }),
  boardCommentAvatar: (dark: boolean): React.CSSProperties => ({
    width: 28,
    height: 28,
    borderRadius: '50%',
    background: dark ? '#334155' : '#e5e7eb',
    color: dark ? '#94a3b8' : '#6b7280',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 11,
    fontWeight: 700,
    flexShrink: 0,
  }),
  boardCommentInputRow: (dark: boolean): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    borderTop: `1px solid ${dark ? '#334155' : '#e5e7eb'}`,
    paddingTop: 10,
  }),
  boardCommentInput: (dark: boolean): React.CSSProperties => ({
    flex: 1,
    padding: '8px 12px',
    border: `1px solid ${dark ? '#475569' : '#e2e8f0'}`,
    borderRadius: 20,
    fontSize: 13,
    background: dark ? '#0f172a' : '#f8fafc',
    color: dark ? '#e2e8f0' : '#1e293b',
    outline: 'none',
  }),
  boardCommentSendBtn: (dark: boolean): React.CSSProperties => ({
    padding: '6px 14px',
    border: 'none',
    borderRadius: 16,
    background: dark ? '#475569' : '#3b82f6',
    color: '#fff',
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    flexShrink: 0,
  }),
};
